"""create payments table

Revision ID: a23cc45d27a7
Revises: aab0ba66da1d
Create Date: 2026-03-29 16:20:54.109356

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a23cc45d27a7"
down_revision: Union[str, Sequence[str], None] = "aab0ba66da1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("processor_payment_id", sa.String(), nullable=True),
        sa.Column("processor", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("ledger_transaction_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("ix_payments_created_at", "payments", ["created_at"], unique=False)
    op.create_index(
        "ix_payments_idempotency_key", "payments", ["idempotency_key"], unique=False
    )
    op.create_index(
        "ix_payments_processor_payment_id",
        "payments",
        ["processor_payment_id"],
        unique=False,
    )
    op.create_index("ix_payments_status", "payments", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_status", table_name="payments")
    op.drop_index("ix_payments_processor_payment_id", table_name="payments")
    op.drop_index("ix_payments_idempotency_key", table_name="payments")
    op.drop_index("ix_payments_created_at", table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
