"""add card_id to issuer_authorizations and create controls tables

Revision ID: 48dce01f199e
Revises: ba72d469f03d
Create Date: 2026-04-03 19:56:47.210898

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48dce01f199e"
down_revision: Union[str, Sequence[str], None] = "ba72d469f03d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcc_blocks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("mcc", sa.String(length=4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_mcc_blocks_card_id", "mcc_blocks", ["card_id"], unique=False)
    op.create_index(
        "ix_mcc_blocks_card_id_mcc", "mcc_blocks", ["card_id", "mcc"], unique=True
    )
    op.create_table(
        "velocity_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("max_amount", sa.Integer(), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_velocity_rules_card_id", "velocity_rules", ["card_id"], unique=False
    )
    op.add_column(
        "issuer_authorizations", sa.Column("card_id", sa.UUID(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issuer_authorizations", "card_id")
    op.drop_index("ix_velocity_rules_card_id", table_name="velocity_rules")
    op.drop_table("velocity_rules")
    op.drop_index("ix_mcc_blocks_card_id_mcc", table_name="mcc_blocks")
    op.drop_index("ix_mcc_blocks_card_id", table_name="mcc_blocks")
    op.drop_table("mcc_blocks")
    # ### end Alembic commands ###
