"""add payees and bills tables

Revision ID: 637e756014ea
Revises: c48f08c8fb6a
Create Date: 2026-04-04 20:13:45.062078

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "637e756014ea"
down_revision: Union[str, Sequence[str], None] = "c48f08c8fb6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("payee_type", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("routing_number", sa.String(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payees_payee_type_created_at",
        "payees",
        ["payee_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "bills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payee_id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column("next_due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payee_id"],
            ["payees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bills_payee_id", "bills", ["payee_id"], unique=False)
    op.create_index(
        "ix_bills_status_next_due_date",
        "bills",
        ["status", "next_due_date"],
        unique=False,
    )
    op.create_table(
        "bill_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bill_id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bill_id", "payment_id", name="uq_bill_payments_bill_payment"
        ),
    )
    op.create_index(
        "ix_bill_payments_bill_id_executed_at",
        "bill_payments",
        ["bill_id", "executed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bill_payments_bill_id_executed_at", table_name="bill_payments")
    op.drop_table("bill_payments")
    op.drop_index("ix_bills_status_next_due_date", table_name="bills")
    op.drop_index("ix_bills_payee_id", table_name="bills")
    op.drop_table("bills")
    op.drop_index("ix_payees_payee_type_created_at", table_name="payees")
    op.drop_table("payees")
    # ### end Alembic commands ###
