"""create issuer_authorizations table

Revision ID: 99a737f3b15d
Revises: a23cc45d27a7
Create Date: 2026-04-03 19:26:06.689129

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99a737f3b15d"
down_revision: Union[str, Sequence[str], None] = "a23cc45d27a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issuer_authorizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("decline_reason", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_issuer_authorizations_decision",
        "issuer_authorizations",
        ["decision"],
        unique=False,
    )
    op.create_index(
        "ix_issuer_authorizations_idempotency_key",
        "issuer_authorizations",
        ["idempotency_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_issuer_authorizations_idempotency_key", table_name="issuer_authorizations"
    )
    op.drop_index(
        "ix_issuer_authorizations_decision", table_name="issuer_authorizations"
    )
    op.drop_table("issuer_authorizations")
    # ### end Alembic commands ###
