"""create reconciliation tables

Revision ID: a1fca4410cc7
Revises: e6321ede7823
Create Date: 2026-04-04 19:07:40.816269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fca4410cc7'
down_revision: Union[str, Sequence[str], None] = 'e6321ede7823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked', sa.Integer(), nullable=False),
    sa.Column('mismatches', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_runs_started_at', 'reconciliation_runs', ['started_at'], unique=False)
    op.create_table('reconciliation_discrepancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('processor_payment_id', sa.String(), nullable=False),
    sa.Column('our_status', sa.String(), nullable=False),
    sa.Column('stripe_status', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_discrepancies_payment_id', 'reconciliation_discrepancies', ['payment_id'], unique=False)
    op.create_index('ix_reconciliation_discrepancies_run_id', 'reconciliation_discrepancies', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reconciliation_discrepancies_run_id', table_name='reconciliation_discrepancies')
    op.drop_index('ix_reconciliation_discrepancies_payment_id', table_name='reconciliation_discrepancies')
    op.drop_table('reconciliation_discrepancies')
    op.drop_index('ix_reconciliation_runs_started_at', table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    # ### end Alembic commands ###
