"""create fraud_signals table

Revision ID: af9db6813014
Revises: 7e06f18e9f3e
Create Date: 2026-04-04 18:48:59.350654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9db6813014'
down_revision: Union[str, Sequence[str], None] = '7e06f18e9f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraud_signals_risk_level_flagged_at', 'fraud_signals', ['risk_level', 'flagged_at'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cardholder_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_logs_cardholder_id', 'notification_logs', ['cardholder_id'], unique=False)
    op.create_index('ix_notification_logs_event_type_sent_at', 'notification_logs', ['event_type', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_logs_event_type_sent_at', table_name='notification_logs')
    op.drop_index('ix_notification_logs_cardholder_id', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('ix_fraud_signals_risk_level_flagged_at', table_name='fraud_signals')
    op.drop_table('fraud_signals')
    # ### end Alembic commands ###
