"""create cardholders and cards tables

Revision ID: ba72d469f03d
Revises: 99a737f3b15d
Create Date: 2026-04-03 19:47:24.390703

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba72d469f03d"
down_revision: Union[str, Sequence[str], None] = "99a737f3b15d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cardholders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_cardholders_email", "cardholders", ["email"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cardholder_id", sa.UUID(), nullable=False),
        sa.Column("credit_limit", sa.Integer(), nullable=False),
        sa.Column("available_balance_account_id", sa.UUID(), nullable=False),
        sa.Column("pending_hold_account_id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_four", sa.String(length=4), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cardholder_id"],
            ["cardholders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cards_cardholder_id", "cards", ["cardholder_id"], unique=False)
    op.create_index("ix_cards_status", "cards", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cards_status", table_name="cards")
    op.drop_index("ix_cards_cardholder_id", table_name="cards")
    op.drop_table("cards")
    op.drop_index("ix_cardholders_email", table_name="cardholders")
    op.drop_table("cardholders")
    # ### end Alembic commands ###
