"""add decision_created_at index to issuer_authorizations

Revision ID: c48f08c8fb6a
Revises: a1fca4410cc7
Create Date: 2026-04-04 19:45:27.750215

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c48f08c8fb6a"
down_revision: Union[str, Sequence[str], None] = "a1fca4410cc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_issuer_authorizations_decision_created_at",
        "issuer_authorizations",
        ["decision", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_issuer_authorizations_decision_created_at",
        table_name="issuer_authorizations",
    )
    # ### end Alembic commands ###
